import Head from 'next/head';
import { Header } from '@/components/global/Header';
import { HOME_SUBTITLE, HOME_TITLE } from '@/config/appMessages';
import useAuth from '@/utils/hooks/useAuth';
import { tokenService } from '@/services/auth/tokenService';
import { NextApiRequest, NextPageContext } from 'next';

export default function Home(props: any) {
  const { currentUser, loading, signin, signout } = useAuth();
  return (
    <>
      <Head>
        <title>Engenharia de Concursos</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/images/favicon.svg' />
      </Head>
      <main>
        <Header title={HOME_TITLE} subtitle={HOME_SUBTITLE} />
        <h1>oi</h1>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </main>
    </>
  );
}

export async function getServerSideProps(ctx: ContextNookie) {
  const token = tokenService.get(ctx);
  console.log(token);

  return {
    props: {
      token: token,
    },
  };
}

type ContextNookie =
  | Pick<NextPageContext, 'req'>
  | { req: NextApiRequest }
  | { req: Request }
  | null
  | undefined;
