import Head from 'next/head';
import { Header } from '@/components/global/Header';
import { HOME_SUBTITLE, HOME_TITLE } from '@/config/appMessages';
import useAuth from '@/utils/hooks/useAuth';
import withSession from '@/services/auth/session';

export default function Home(props: any) {
  const { currentUser, loading, signin, signout } = useAuth();
  return (
    <>
      <Head>
        <title>Engenharia de Concursos</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/images/favicon.svg' />
      </Head>
      <main>
        <Header title={HOME_TITLE} subtitle={HOME_SUBTITLE} />
        <h1>oi</h1>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </main>
    </>
  );
}

export const getServerSideProps = withSession((ctx: any) => {
  const context = ctx as unknown as ContextReq;
  return {
    props: {
      session: context.req.session,
    },
  };
});

type ContextReq = {
  req: { session: object };
};

// export async function getServerSideProps(ctx: ContextNookie) {
//   try {
//     const session = await authService.getSession(ctx);
//     return {
//       props: {
//         token: session,
//       },
//     };
//   } catch (error) {
//     return {
//       redirect: {
//         permanent: false,
//         destination: '/login',
//       },
//     };
//   }
// }
